// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5dq6LnR3VVBr21oM2A4UkDTUza8egLo',
    appId: '1:221282660647:web:507c899b91089c8146b902',
    messagingSenderId: '221282660647',
    projectId: 'university-journal',
    authDomain: 'university-journal.firebaseapp.com',
    storageBucket: 'university-journal.firebasestorage.app',
    measurementId: 'G-Z2D03ELF0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnmGiWRWpxnNwejtbcEpyXv9hOd28S2g',
    appId: '1:221282660647:android:acfed8ae807282e546b902',
    messagingSenderId: '221282660647',
    projectId: 'university-journal',
    storageBucket: 'university-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV3pu7S5KyyKZJQyKX5_d0Q_NUJQDKbuA',
    appId: '1:221282660647:ios:aa2d8733f237124d46b902',
    messagingSenderId: '221282660647',
    projectId: 'university-journal',
    storageBucket: 'university-journal.firebasestorage.app',
    iosBundleId: 'com.example.universityJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV3pu7S5KyyKZJQyKX5_d0Q_NUJQDKbuA',
    appId: '1:221282660647:ios:aa2d8733f237124d46b902',
    messagingSenderId: '221282660647',
    projectId: 'university-journal',
    storageBucket: 'university-journal.firebasestorage.app',
    iosBundleId: 'com.example.universityJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd5dq6LnR3VVBr21oM2A4UkDTUza8egLo',
    appId: '1:221282660647:web:17e9ebde9ffdfb2446b902',
    messagingSenderId: '221282660647',
    projectId: 'university-journal',
    authDomain: 'university-journal.firebaseapp.com',
    storageBucket: 'university-journal.firebasestorage.app',
    measurementId: 'G-MY2JQMY9EB',
  );
}
